const REFERENCE_DATA = {
    luau: [
        {name: 'local', desc: 'تعريف متغير محلي', code: 'local x = 10'},
        {name: 'function', desc: 'تعريف دالة', code: 'local function add(a, b)\n    return a + b\nend'},
        {name: 'if/then/else', desc: 'شروط', code: 'if x > 5 then\n    print("كبير")\nelse\n    print("صغير")\nend'},
        {name: 'for', desc: 'حلقة تكرارية', code: 'for i = 1, 10 do\n    print(i)\nend'},
        {name: 'while', desc: 'حلقة شرطية', code: 'while condition do\n    -- ...\nend'},
        {name: 'repeat/until', desc: 'تكرار حتى شرط', code: 'repeat\n    -- ...\nuntil condition'},
        {name: 'return', desc: 'إرجاع قيمة', code: 'return value'},
        {name: 'break', desc: 'الخروج من الحلقة', code: 'break'},
        {name: 'continue', desc: 'التكرار التالي (Luau)', code: 'continue'},
        {name: 'pairs', desc: 'تكرار جدول', code: 'for k, v in pairs(table) do end'},
        {name: 'ipairs', desc: 'تكرار مصفوفة', code: 'for i, v in ipairs(array) do end'},
        {name: 'pcall', desc: 'استدعاء محمي', code: 'local ok, err = pcall(function() end)'},
        {name: 'require', desc: 'استيراد وحدة', code: 'local Module = require(path)'},
        {name: 'typeof', desc: 'نوع القيمة', code: 'print(typeof(part)) -- "Instance"'},
        {name: 'type', desc: 'نوع البيانات', code: 'print(type(42)) -- "number"'},
        {name: 'tostring', desc: 'تحويل لنص', code: 'tostring(42) -- "42"'},
        {name: 'tonumber', desc: 'تحويل لرقم', code: 'tonumber("42") -- 42'},
        {name: 'math', desc: 'مكتبة الرياضيات', code: 'math.random(1, 100)\nmath.floor(3.7) -- 3\nmath.abs(-5) -- 5\nmath.rad(90) -- تحويل لراديان'},
        {name: 'string', desc: 'مكتبة النصوص', code: 'string.len("hello") -- 5\nstring.sub("hello", 1, 3) -- "hel"\nstring.upper("hello") -- "HELLO"'},
        {name: 'table', desc: 'مكتبة الجداول', code: 'table.insert(t, value)\ntable.remove(t, index)\ntable.sort(t)\n#t -- طول الجدول'},
    ],
    instance: [
        {name: 'Instance.new', desc: 'إنشاء كائن جديد', code: 'local part = Instance.new("Part")\npart.Parent = workspace'},
        {name: ':Clone()', desc: 'نسخ كائن', code: 'local clone = original:Clone()'},
        {name: ':Destroy()', desc: 'حذف كائن', code: 'part:Destroy()'},
        {name: ':FindFirstChild', desc: 'بحث فوري عن ابن', code: 'local p = parent:FindFirstChild("Name")'},
        {name: ':WaitForChild', desc: 'انتظار ظهور ابن', code: 'local p = parent:WaitForChild("Name", 10)'},
        {name: ':GetChildren', desc: 'جلب الأبناء', code: 'local kids = parent:GetChildren()'},
        {name: ':GetDescendants', desc: 'جلب كل التراث', code: 'local all = parent:GetDescendants()'},
        {name: ':IsA', desc: 'التحقق من النوع', code: 'if part:IsA("BasePart") then end'},
        {name: '.Name', desc: 'اسم الكائن', code: 'part.Name = "MyPart"'},
        {name: '.Parent', desc: 'الأب', code: 'part.Parent = workspace'},
        {name: '.ClassName', desc: 'نوع الكلاس', code: 'print(part.ClassName) -- "Part"'},
        {name: '.Anchored', desc: 'ثابت', code: 'part.Anchored = true'},
        {name: '.CanCollide', desc: 'التصادم', code: 'part.CanCollide = true'},
        {name: '.Position', desc: 'الموقع', code: 'part.Position = Vector3.new(0,10,0)'},
        {name: '.Size', desc: 'الحجم', code: 'part.Size = Vector3.new(4,1,4)'},
        {name: '.CFrame', desc: 'الموقع والدوران', code: 'part.CFrame = CFrame.new(0,10,0)'},
        {name: '.Color', desc: 'اللون', code: 'part.Color = Color3.new(1,0,0)'},
        {name: '.Transparency', desc: 'الشفافية', code: 'part.Transparency = 0.5'},
        {name: '.Material', desc: 'المادة', code: 'part.Material = Enum.Material.Neon'},
        {name: '.BrickColor', desc: 'اللون التقليدي', code: 'part.BrickColor = BrickColor.new("Bright red")'},
        {name: '.Shape', desc: 'الشكل', code: 'part.Shape = Enum.PartType.Ball'},
        {name: '.Velocity', desc: 'السرعة', code: 'part.Velocity = Vector3.new(0,50,0)'},
    ],
    services: [
        {name: 'Players', desc: 'خدمة اللاعبين', code: 'local Players = game:GetService("Players")\nPlayers.PlayerAdded:Connect(function(player)\n    print(player.Name)\nend)'},
        {name: 'TweenService', desc: 'الحركات السلسة', code: 'local TS = game:GetService("TweenService")\nlocal tween = TS:Create(part, TweenInfo.new(2), {Position=Vector3.new(0,20,0)})\ntween:Play()'},
        {name: 'RunService', desc: 'تحديث كل فريم', code: 'local RS = game:GetService("RunService")\nRS.Heartbeat:Connect(function(dt)\n    part.Position += Vector3.new(0, dt*5, 0)\nend)'},
        {name: 'UserInputService', desc: 'مخرجات المستخدم', code: 'local UIS = game:GetService("UserInputService")\nUIS.InputBegan:Connect(function(input, gp)\n    if not gp and input.KeyCode == Enum.KeyCode.E then\n        print("E pressed!")\n    end\nend)'},
        {name: 'DataStoreService', desc: 'حفظ البيانات', code: 'local DSS = game:GetService("DataStoreService")\nlocal store = DSS:GetDataStore("MyData")\nstore:SetAsync("key", "value")\nlocal data = store:GetAsync("key")'},
        {name: 'ReplicatedStorage', desc: 'المخزن المشترك', code: 'local RS = game:GetService("ReplicatedStorage")'},
        {name: 'ServerScriptService', desc: 'سكربتات الخادم', code: ''},
        {name: 'Lighting', desc: 'الإضاءة والجو', code: 'local L = game:GetService("Lighting")\nL.Ambient = Color3.fromRGB(50,50,50)\nL.Brightness = 2'},
        {name: 'Debris', desc: 'حذف مؤقت', code: 'local D = game:GetService("Debris")\nD:AddItem(part, 5) -- حذف بعد 5 ثواني'},
        {name: 'PathfindingService', desc: 'إيجاد المسارات', code: 'local PS = game:GetService("PathfindingService")\nlocal path = PS:CreatePath({AgentRadius=2, AgentHeight=5, AgentCanJump=true})'},
        {name: 'CollectionService', desc: 'تجميع الكائنات', code: 'local CS = game:GetService("CollectionService")\nCS:AddTag(part, "MyTag")\nlocal tagged = CS:GetTagged("MyTag")'},
        {name: 'MarketplaceService', desc: 'المتجر والمشتريات', code: 'local MPS = game:GetService("MarketplaceService")\nMPS:PromptGamePassPurchase(player, passId)'},
        {name: 'PhysicsService', desc: 'الفيزياء والتصادم', code: 'local PS = game:GetService("PhysicsService")\nPS:RegisterCollisionGroup("Players")'},
        {name: 'TeleportService', desc: 'النقل بين الألعاب', code: 'local TS = game:GetService("TeleportService")\nTS:Teleport(placeId, player)'},
    ],
    datatypes: [
        {name: 'Vector3', desc: 'إحداثيات ثلاثية الأبعاد', code: 'local v = Vector3.new(1, 2, 3)\nprint(v.X, v.Y, v.Z)\nlocal d = (a - b).Magnitude'},
        {name: 'Vector2', desc: 'إحداثيات ثنائية الأبعاد', code: 'local v = Vector2.new(100, 200)'},
        {name: 'CFrame', desc: 'مصفوفة الموقع والدوران', code: 'local cf = CFrame.new(0, 10, 0)\nlocal rot = CFrame.Angles(0, math.rad(90), 0)'},
        {name: 'Color3', desc: 'اللون', code: 'local c = Color3.new(1, 0, 0)\nlocal c2 = Color3.fromRGB(255, 0, 0)\nlocal c3 = Color3.fromHSV(0, 1, 1)'},
        {name: 'UDim2', desc: 'البعد مع وحدة', code: 'local u = UDim2.new(0.5, 0, 0.5, 0)\n-- 50% من العرض والارتفاع'},
        {name: 'Enum', desc: 'قيم محددة', code: 'Enum.Material.Neon\nEnum.PartType.Block\nEnum.EasingStyle.Quad'},
        {name: 'TweenInfo', desc: 'معلومات الحركة', code: 'TweenInfo.new(2, Enum.EasingStyle.Quad, Enum.EasingDirection.Out)'},
        {name: 'BrickColor', desc: 'اللون التقليدي', code: 'BrickColor.new("Bright red")\nBrickColor.New("Really blue")'},
        {name: 'NumberRange', desc: 'نطاق أرقام', code: 'NumberRange.new(1, 10)'},
        {name: 'RaycastParams', desc: 'معاملات الشعاع', code: 'local params = RaycastParams.new()\nparams.FilterType = Enum.RaycastFilterType.Exclude\nparams.FilterDescendantsInstances = {part}'},
    ],
    events: [
        {name: '.Touched', desc: 'عند لمس الكائن', code: 'part.Touched:Connect(function(hit)\n    print(hit.Name)\nend)'},
        {name: '.Changed', desc: 'عند تغيير خاصية', code: 'part.Changed:Connect(function(prop)\n    print(prop .. " changed")\nend)'},
        {name: '.ChildAdded', desc: 'عند إضافة ابن', code: 'parent.ChildAdded:Connect(function(child)\n    print(child.Name .. " added")\nend)'},
        {name: '.ChildRemoved', desc: 'عند حذف ابن', code: 'parent.ChildRemoved:Connect(function(child)\n    print(child.Name .. " removed")\nend)'},
        {name: '.AncestryChanged', desc: 'عند تغيير الأب', code: 'inst.AncestryChanged:Connect(function(parent)\n    print("Parent changed")\nend)'},
        {name: '.Humanoid.Died', desc: 'عند موت الشخصية', code: 'humanoid.Died:Connect(function()\n    print("Dead!")\nend)'},
        {name: '.Humanoid.HealthChanged', desc: 'عند تغيير الصحة', code: 'humanoid.HealthChanged:Connect(function(health)\n    print("HP: " .. health)\nend)'},
        {name: '.PlayerAdded', desc: 'عند دخول لاعب', code: 'Players.PlayerAdded:Connect(function(player)\n    print(player.Name .. " joined")\nend)'},
        {name: '.PlayerRemoving', desc: 'عند خروج لاعب', code: 'Players.PlayerRemoving:Connect(function(player)\n    print(player.Name .. " left")\nend)'},
        {name: '.OnServerEvent', desc: 'استقبال من العميل', code: 'event.OnServerEvent:Connect(function(player, data)\n    print(data)\nend)'},
        {name: '.OnClientEvent', desc: 'استقبال من الخادم', code: 'event.OnClientEvent:Connect(function(data)\n    print(data)\nend)'},
        {name: '.Heartbeat', desc: 'كل فريم (RunService)', code: 'RunService.Heartbeat:Connect(function(dt)\n    -- كل فريم\nend)'},
    ],
    gui: [
        {name: 'ScreenGui', desc: 'شاشة GUI أساسية', code: 'local gui = Instance.new("ScreenGui")\ngui.Parent = player.PlayerGui'},
        {name: 'Frame', desc: 'إطار', code: 'local frame = Instance.new("Frame")\nframe.Size = UDim2.new(0.3, 0, 0.3, 0)\nframe.BackgroundColor3 = Color3.fromRGB(30,40,60)'},
        {name: 'TextLabel', desc: 'نص للعرض', code: 'local label = Instance.new("TextLabel")\nlabel.Text = "مرحباً"\nlabel.TextColor3 = Color3.new(1,1,1)'},
        {name: 'TextButton', desc: 'زر', code: 'local btn = Instance.new("TextButton")\nbtn.Text = "اضغط"\nbtn.MouseButton1Click:Connect(function() end)'},
        {name: 'TextBox', desc: 'حقل إدخال', code: 'local box = Instance.new("TextBox")\nbox.PlaceholderText = "اكتب هنا..."\nbox.FocusLost:Connect(function(enter) end)'},
        {name: 'ImageLabel', desc: 'صورة', code: 'local img = Instance.new("ImageLabel")\nimg.Image = "rbxassetid://12345678"'},
        {name: 'ScrollingFrame', desc: 'إطار قابل للتمرير', code: 'local sf = Instance.new("ScrollingFrame")\nsf.CanvasSize = UDim2.new(0, 0, 2, 0)'},
        {name: 'UICorner', desc: 'زوايا مستديرة', code: 'local c = Instance.new("UICorner")\nc.CornerRadius = UDim.new(0, 8)'},
        {name: 'UIStroke', desc: 'حدود', code: 'local s = Instance.new("UIStroke")\ns.Color = Color3.fromRGB(0, 180, 216)\ns.Thickness = 2'},
        {name: 'UIGradient', desc: 'تدرج لوني', code: 'local g = Instance.new("UIGradient")\ng.Color = ColorSequence.new(Color3.new(1,0,0), Color3.new(0,0,1))'},
        {name: 'UIListLayout', desc: 'تخطيط قائمة', code: 'local l = Instance.new("UIListLayout")\nl.Padding = UDim.new(0, 5)'},
        {name: 'UIPadding', desc: 'حشوة', code: 'local p = Instance.new("UIPadding")\np.PaddingTop = UDim.new(0, 10)'},
    ],
    physics: [
        {name: 'Raycast', desc: 'إرسال شعاع لاكتشاف الأشياء', code: 'local result = workspace:Raycast(origin, direction, params)\nif result then\n    print(result.Instance, result.Position)\nend'},
        {name: 'BodyVelocity', desc: 'إضافة سرعة جسدية', code: 'local bv = Instance.new("BodyVelocity")\nbv.Velocity = Vector3.new(0, 50, 0)\nbv.MaxForce = Vector3.new(1e5, 1e5, 1e5)\nbv.P = 1000\nbv.Parent = part\ndebris:AddItem(bv, 0.2)'},
        {name: 'BodyGyro', desc: 'إضافة دوران جسدي', code: 'local bg = Instance.new("BodyGyro")\nbg.CFrame = CFrame.Angles(0, math.rad(90), 0)\nbg.MaxTorque = Vector3.new(1e5, 1e5, 1e5)\nbg.Parent = part'},
        {name: 'BodyForce', desc: 'إضافة قوة جسدية', code: 'local bf = Instance.new("BodyForce")\nbf.Force = Vector3.new(0, 5000, 0)\nbf.Parent = part'},
        {name: 'WeldConstraint', desc: 'ربط جسيمات معاً', code: 'local w = Instance.new("WeldConstraint")\nw.Part0 = part1\nw.Part1 = part2\nw.Parent = part1'},
        {name: 'VectorForce', desc: 'قوة اتجاهية حديثة', code: 'local vf = Instance.new("VectorForce")\nvf.Force = Vector3.new(0, 100, 0)\nvf.Attachment0 = attachment\nvf.Parent = part'},
        {name: 'LinearVelocity', desc: 'سرعة خطية حديثة', code: 'local lv = Instance.new("LinearVelocity")\nlv.VelocityConstraintMode = Enum.VelocityConstraintMode.Vector\nlv.VectorVelocity = Vector3.new(0, 50, 0)\nlv.MaxForce = 10000\nlv.Attachment0 = attachment\nlv.Parent = part'},
        {name: 'AlignOrientation', desc: 'محاذاة دوران حديثة', code: 'local ao = Instance.new("AlignOrientation")\nao.PrimaryAxis = Vector3.new(0, 1, 0)\nao.MaxTorque = 10000\nao.Attachment0 = attachment\nao.Parent = part'},
        {name: 'BallSocketConstraint', desc: 'مفصل كرة', code: 'local bs = Instance.new("BallSocketConstraint")\nbs.Attachment0 = att0\nbs.Attachment1 = att1\nbs.LimitsEnabled = true\nbs.UpperAngle = 45\nbs.Parent = part'},
        {name: 'HingeConstraint', desc: 'مفصل مفصلي', code: 'local hinge = Instance.new("HingeConstraint")\nhinge.Attachment0 = att0\nhinge.Attachment1 = att1\nhinge.ActuatorType = Enum.ActuatorType.Motor\nhinge.AngularVelocity = 2\nhinge.MaxTorque = 10000\nhinge.Parent = part'},
        {name: 'Vector3.Magnitude', desc: 'حساب المسافة بين نقطتين', code: 'local dist = (partA.Position - partB.Position).Magnitude'},
        {name: 'Vector3.Unit', desc: 'تحويل المتجه لواحد', code: 'local direction = (target - origin).Unit'},
        {name: 'Vector3.Lerp', desc: 'التحريك الخلطي', code: 'local pos = Vector3.new(0, 0, 0):Lerp(Vector3.new(10, 10, 10), 0.5)'},
        {name: 'CFrame.lookAt', desc: 'النظر لاتجاه معين', code: 'local cf = CFrame.lookAt(part.Position, target.Position)'},
        {name: 'CFrame:Lerp', desc: 'التحريك الخلطي', code: 'part.CFrame = part.CFrame:Lerp(targetCF, 0.1)'},
        {name: 'workspace:GetPartBoundsInRadius', desc: 'العثور على أجزاء في نطاق', code: 'local parts = workspace:GetPartBoundsInRadius(position, radius, overlapParams)'},
        {name: 'workspace:GetPartBoundsInBox', desc: 'العثور على أجزاء في صندوق', code: 'local parts = workspace:GetPartBoundsInBox(cframe, size, overlapParams)'},
    ],
    advanced: [
        {name: 'task.wait', desc: 'الانتظار بشكل حديث (الأفضل من wait)', code: 'task.wait(2) -- انتظار ثانيتين'},
        {name: 'task.spawn', desc: 'تنفيذ في خيط منفصل', code: 'task.spawn(function()\n    -- كود في خيط منفصل\n    task.wait(1)\n    print("تم بعد ثانية!")\nend)'},
        {name: 'task.delay', desc: 'تأخير التنفيذ', code: 'task.delay(5, function()\n    print("بعد 5 ثواني!")\nend)'},
        {name: 'task.defer', desc: 'تأخير للفريم التالي', code: 'task.defer(function()\n    -- يُنفذ في الفريم التالي\n    print("Next frame!")\nend)'},
        {name: 'table.clone', desc: 'نسخ جدول', code: 'local original = {1, 2, 3}\nlocal copy = table.clone(original)'},
        {name: 'table.freeze', desc: 'تجميد جدول', code: 'local data = {a=1, b=2}\ntable.freeze(data)\ndata.a = 3 -- خطأ! الجدول مجمّد'},
        {name: 'table.find', desc: 'البحث عن قيمة في جدول', code: 'local index = table.find({10, 20, 30}, 20) -- 2'},
        {name: 'table.clear', desc: 'مسح كل عناصر الجدول', code: 'local t = {1, 2, 3}\ntable.clear(t) -- {}'},
        {name: 'typeof vs type', desc: 'الفرق بين typeof و type', code: 'print(type(part))        -- "userdata"\nprint(typeof(part))      -- "Instance"\nprint(type(42))          -- "number"\nprint(typeof(42))        -- "number"'},
        {name: 'pcall متقدم', desc: 'معالجة أخطاء مع تفاصيل', code: 'local ok, result = pcall(function()\n    return store:GetAsync("key")\nend)\nif ok then\n    print("البيانات:", result)\nelse\n    warn("خطأ:", tostring(result))\nend'},
        {name: 'setmetatable', desc: 'تعيين metatable', code: 'local MyClass = {}\nMyClass.__index = MyClass\n\nfunction MyClass.new(name)\n    local self = setmetatable({}, MyClass)\n    self.name = name\n    return self\nend\n\nfunction MyClass:getName()\n    return self.name\nend'},
        {name: 'Instance attributes', desc: 'خصائص مخصصة', code: 'part:SetAttribute("Damage", 25)\npart:SetAttribute("Level", 3)\n\nlocal dmg = part:GetAttribute("Damage")\nprint(dmg) -- 25\n\npart:GetAttributeChangedSignal("Damage"):Connect(function()\n    print("Damage changed!")\nend)'},
        {name: 'CollectionService Tags', desc: 'تصنيف الكائنات بالوسوم', code: 'local CS = game:GetService("CollectionService")\n\n-- إضافة وسوم\nCS:AddTag(part, "Lava")\nCS:AddTag(part, "Collectible")\n\n-- البحث\nlocal lavas = CS:GetTagged("Lava")\nfor _, lava in ipairs(lavas) do\n    print(lava.Name)\nend\n\n-- مراقبة\nCS:GetInstanceAddedSignal("Lava"):Connect(function(instance)\n    print(instance.Name .. " added as Lava!")\nend)'},
        {name: 'ProximityPrompt', desc: 'إشارة تفاعل قريبة', code: 'local pp = Instance.new("ProximityPrompt")\npp.ActionText = "افتح"\npp.ObjectText = "صندوق"\npp.MaxActivationDistance = 10\npp.HoldDuration = 1\npp.KeyboardKeyCode = Enum.KeyCode.E\npp.Parent = part\n\npp.Triggered:Connect(function(player)\n    print(player.Name .. " interacted!")\nend)'},
        {name: 'ClickDetector', desc: 'كاشف النقر', code: 'local cd = Instance.new("ClickDetector")\ncd.MaxActivationDistance = 15\ncd.CursorIcon = "rbxasset://textures/advCursor-openHand.png"\ncd.Parent = part\n\ncd.MouseClick:Connect(function(player)\n    print(player.Name .. " clicked!")\nend)\n\ncd.MouseHoverEnter:Connect(function(player)\n    print(player.Name .. " hovering!")\nend)'},
        {name: 'Attribute system', desc: 'نظام الخصائص المخصصة', code: 'local Players = game:GetService("Players")\n\nPlayers.PlayerAdded:Connect(function(player)\n    -- إضافة خصائص مخصصة للاعب\n    player:SetAttribute("Coins", 0)\n    player:SetAttribute("Level", 1)\n    player:SetAttribute("VIP", false)\n    \n    -- مراقبة التغييرات\n    player:GetAttributeChangedSignal("Coins"):Connect(function()\n        print("Coins:", player:GetAttribute("Coins"))\n    end)\nend)'},
    ],
    math_reference: [
        {name: 'math.abs', desc: 'القيمة المطلقة', code: 'math.abs(-5) -- 5'},
        {name: 'math.floor', desc: 'التقريب للأسفل', code: 'math.floor(3.7) -- 3'},
        {name: 'math.ceil', desc: 'التقريب للأعلى', code: 'math.ceil(3.2) -- 4'},
        {name: 'math.round', desc: 'التقريب العادي', code: 'math.round(3.5) -- 4'},
        {name: 'math.min', desc: 'أصغر قيمة', code: 'math.min(3, 7, 1) -- 1'},
        {name: 'math.max', desc: 'أكبر قيمة', code: 'math.max(3, 7, 1) -- 7'},
        {name: 'math.clamp', desc: 'تقييد النطاق', code: 'math.clamp(15, 0, 10) -- 10'},
        {name: 'math.random', desc: 'رقم عشوائي', code: 'math.random(1, 100) -- رقم عشوائي'},
        {name: 'math.pi', desc: 'ثابت باي', code: 'math.pi -- 3.14159...'},
        {name: 'math.sqrt', desc: 'الجذر التربيعي', code: 'math.sqrt(16) -- 4'},
        {name: 'math.rad', desc: 'تحويل لراديان', code: 'math.rad(90) -- 1.5707...'},
        {name: 'math.deg', desc: 'تحويل لدرجات', code: 'math.deg(math.pi) -- 180'},
        {name: 'math.sin', desc: 'الجيب', code: 'math.sin(math.rad(90)) -- 1'},
        {name: 'math.cos', desc: 'جيب التمام', code: 'math.cos(0) -- 1'},
        {name: 'math.atan2', desc: 'العلاقة المماسية العكسية', code: 'math.atan2(1, 0) -- π/2'},
        {name: 'math.huge', desc: 'قيمة لا نهائية', code: 'math.huge -- inf'},
    ],
    string_reference: [
        {name: 'string.len', desc: 'طول النص', code: 'string.len("hello") -- 5'},
        {name: 'string.sub', desc: 'استخراج جزء', code: 'string.sub("hello", 1, 3) -- "hel"'},
        {name: 'string.find', desc: 'البحث عن نمط', code: 'string.find("hello world", "world") -- 7, 11'},
        {name: 'string.rep', desc: 'تكرار النص', code: 'string.rep("ha", 3) -- "hahaha"'},
        {name: 'string.reverse', desc: 'عكس النص', code: 'string.reverse("hello") -- "olleh"'},
        {name: 'string.lower', desc: 'تحويل لحروف صغيرة', code: 'string.lower("HELLO") -- "hello"'},
        {name: 'string.upper', desc: 'تحويل لحروف كبيرة', code: 'string.upper("hello") -- "HELLO"'},
        {name: 'string.match', desc: 'مطابقة نمط', code: 'string.match("age: 25", "%d+") -- "25"'},
        {name: 'string.gsub', desc: 'استبدال', code: 'string.gsub("hello", "l", "r") -- "herro"'},
        {name: 'string.split', desc: 'تقسيم النص', code: 'string.split("a,b,c", ",") -- {"a", "b", "c"}'},
        {name: 'string.trim', desc: 'حذف المسافات', code: 'string.trim("  hello  ") -- "hello"'},
        {name: 'string.format', desc: 'تنسيق النص', code: 'string.format("Name: %s, Age: %d", "Ahmed", 25)'},
    ],
    coding_tips: [
        {name: 'استخدم local دائماً', desc: 'تجنب المتغيرات العامة', code: 'local x = 10 -- صحيحاً\nx = 10 -- سيء'},
        {name: 'استخدم task بدلاً من wait', desc: 'task.wait() أكثر استقراراً', code: 'task.wait(1) -- حديث\nwait(1) -- قديم'},
        {name: 'استخدم pcall مع DataStore', desc: 'حماية من الأخطاء', code: 'pcall(function()\n    store:SetAsync(key, value)\nend)'},
        {name: 'استخدم WaitForChild', desc: 'انتظار تحميل الكائنات', code: 'local p = parent:WaitForChild("Name", 10)'},
        {name: 'التحقق من اللاعب على الخادم', desc: 'أمان البيانات', code: 'local player = Players:GetPlayerFromCharacter(char)\nif not player then return end'},
        {name: 'استخدم typeof بدلاً من type', desc: 'نوع Roblox الأدق', code: 'typeof(part) -- "Instance"\ntype(part) -- "userdata"'},
        {name: 'تجنب WaitForChild في الحلقات', desc: 'تحسين الأداء', code: 'local cached = parent:GetChildren()\nfor _, child in ipairs(cached) do end'},
        {name: 'استخدم Debris للأغراض المؤقتة', desc: 'حذف تلقائي', code: 'Debris:AddItem(effect, 2)'},
        {name: 'افصل بين Logix و View', desc: 'تنظيم الكود', code: '-- Modules للمنطق\n-- SGUI للعرض'},
        {name: 'استخدم Attributes', desc: 'بيانات مخصصة بدون StringValue', code: 'part:SetAttribute("Damage", 25)\nlocal dmg = part:GetAttribute("Damage")'},
    ]
};
